Repository immobiliare/RealHTTP, pull requests merged in 2022-11, with the labels that each got.

#72 HTTPAltRequestValidator all methods and properties should be marked as open to be customizable
  Sources/RealHTTP/Client/Internal/HTTPResponseValidator/HTTPAltRequestValidator.swift
Labels: enhancement

#68 Fix: withTaskCancellationHandler deprecation warning
  Sources/RealHTTP/Client/Internal/HTTPDataLoader/HTTPDataLoader.swift
  Tests/RealHTTPTests/Requests+Tests.swift
Labels: bug, enhancement

#69 Add a new retry strategy to allow performing async task before retrying a request
  Sources/RealHTTP/Client/Internal/HTTPDataLoader/HTTPDataLoader.swift
  Sources/RealHTTP/Client/Internal/HTTPResponseValidator/HTTPValidator.swift
  Tests/RealHTTPTests/Requests+Tests.swift
Labels: enhancement

#73 Explicitly specify boolEncoding and arrayEncoding strategies when adding parameters in bulk via formURLEncodedBody()
  Sources/RealHTTP/Client/Internal/HTTPBody/URLParametersData/HTTPBody+QueryString.swift
Labels: enhancement

#74 #70: HTTP Stubbing: URL matcher incorrectly strips port when using "ignore query parameters" option
  Sources/RealHTTP/Client/Internal/Other Structures/Foundation+Extensions/Foundation+Extension.swift
  Tests/RealHTTPTests/Requests+Tests.swift
Labels: bug
