Repository immobiliare/RealHTTP, pull requests merged in 2022-03, with the labels that each got.

#22 Release 1.2.0
  Documentation/2.Build_Request.md
  RealHTTP.podspec
  Sources/RealHTTP/Client/HTTPClient/HTTPClient.swift
  Sources/RealHTTP/Client/HTTPRequest/HTTPRequest.swift
  Sources/RealHTTP/Client/HTTPResponse/HTTPResponse.swift
  Sources/RealHTTP/Client/Internal/HTTPBody/HTTPBody.swift
  Sources/RealHTTP/Client/Internal/HTTPBody/HTTPSerializableBody.swift
  Sources/RealHTTP/Client/Internal/HTTPBody/JSON/HTTPBody+JSON.swift
  Sources/RealHTTP/Client/Internal/HTTPBody/JSON/JSONEncodable.swift
  Sources/RealHTTP/Client/Internal/HTTPBody/JSON/JSONSerializable.swift
  Sources/RealHTTP/Client/Internal/HTTPBody/Multipart/HTTPBody+Multipart.swift
  Sources/RealHTTP/Client/Internal/HTTPBody/Multipart/Support/MultipartForm.swift
  Sources/RealHTTP/Client/Internal/HTTPBody/Stream/HTTPBody+Stream.swift
  Sources/RealHTTP/Client/Internal/HTTPBody/Stream/HTTPStreamContent.swift
  Sources/RealHTTP/Client/Internal/HTTPBody/Stream/StreamContent.swift
  Sources/RealHTTP/Client/Internal/HTTPBody/URLParametersData/HTTPBody+QueryString.swift
  Sources/RealHTTP/Client/Internal/HTTPBody/URLParametersData/URLParametersData.swift
  Sources/RealHTTP/Client/Internal/HTTPDataLoader/HTTPDataLoader.swift
  Sources/RealHTTP/Client/Internal/HTTPResponseTransform/HTTPResponseTransform.swift
  Sources/RealHTTP/Client/Internal/Other Structures/Foundation+Extensions/URLRequest+Extension.swift
  Sources/RealHTTP/Client/Internal/Other Structures/Headers/HTTPHeaders.swift
  Sources/RealHTTP/Client/Internal/Other Structures/cURLHelper.swift
  Sources/RealHTTP/RealHTTP.swift
  Tests/RealHTTPTests/Requests+Tests.swift
Labels: bug, enhancement

#30 #26 - Added shortcuts to cast body to common structures
  Sources/RealHTTP/Client/Internal/HTTPBody/HTTPBody.swift
  Sources/RealHTTP/Client/Internal/HTTPBody/JSON/JSONEncodable.swift
  Sources/RealHTTP/Client/Internal/HTTPBody/JSON/JSONSerializable.swift
  Sources/RealHTTP/Client/Internal/HTTPBody/Multipart/HTTPBody+Multipart.swift
  Sources/RealHTTP/Client/Internal/HTTPBody/Stream/HTTPBody+Stream.swift
  Sources/RealHTTP/Client/Internal/HTTPBody/URLParametersData/HTTPBody+QueryString.swift
  Sources/RealHTTP/Client/Internal/HTTPBody/URLParametersData/URLParametersData.swift
Labels: enhancement

#29 #27 - Fixes for retry mechanism of the HTTPAltRequestValidator
  Sources/RealHTTP/Client/HTTPResponse/HTTPResponse.swift
  Sources/RealHTTP/Client/Internal/HTTPDataLoader/HTTPDataLoader.swift
  Sources/RealHTTP/Client/Internal/HTTPResponseValidator/HTTPAltRequestValidator.swift
  Sources/RealHTTP/Client/Internal/Other Structures/HTTPError.swift
  Tests/RealHTTPTests/Requests+Tests.swift
Labels: bug, enhancement

#32 Make HTTPStubResponse initializer public
  Sources/RealHTTP/Stubber/DataTypes/Stub Response/HTTPStubResponse.swift
Labels: bug

#36 #35: queryParams fix in HTTPClient's when HTTPRequest's queryParams are nil
  Sources/RealHTTP/Client/HTTPRequest/HTTPRequest.swift
  Tests/RealHTTPTests/Requests+Tests.swift
Labels: bug

#37 #34 Fix for custom error dispatch for decode() and throws
  Sources/RealHTTP/Client/HTTPResponse/HTTPResponse.swift
  Sources/RealHTTP/Client/Internal/HTTPDataLoader/HTTPDataLoader.swift
  Sources/RealHTTP/Client/Internal/HTTPResponseValidator/HTTPAltRequestValidator.swift
  Sources/RealHTTP/Client/Internal/Other Structures/HTTPError.swift
  Tests/RealHTTPTests/Requests+Tests.swift
Labels: bug, enhancement
