Repository immobiliare/RealHTTP, pull requests merged in 2023-02, with the labels that each got.

#77 Typos and readability suggestions
  Documentation/1.Introduction.md
  Documentation/2.Build_Request.md
  Documentation/3.Advanced_HTTPClient.md
  Documentation/4.Handle_LargeData_Requests.md
  Documentation/6.Other_Debugging_Tools.md
  Documentation/7.Stubber.md
Labels: documentation

#83 #82: removed ignore condition
  Sources/RealHTTP/Client/Internal/Other Structures/cURLHelper.swift
Labels: enhancement

#85 Added Set-Cookie option in HTTPHeaders
  Sources/RealHTTP/Client/Internal/Other Structures/Headers/HTTPHeaderElement+Name.swift
Labels: enhancement

#84 Fix download percentage not always getting to 1 due to rounding errors
  Sources/RealHTTP/Client/Internal/Other Structures/HTTPProgress.swift
Labels: bug
